name: weather_app
description: A Flutter Weather app using best practices by @masreplay
publish_to: 'none'
version: 0.1.1
repository: https://github.com/masreplay/weather_app

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.2
  auto_route: ^7.8.2
  flutter_localizations:
    sdk: flutter
  intl: any
  gap: ^3.0.1
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1
  auto_route_generator: ^7.3.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/hour/